pinot_shop/src/menu/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/menu/', views.admin_menu, name="menu_admin"),
]

pinot_shop/src/pino_acryl/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.http import HttpResponse

urlpatterns = [
    path('', include('menu.urls')),
    path('', include('shop_management.urls')),
    path('shop_admin/', include('shop_admin.urls')),
    path('sample_image/', include('sample_image.urls')),
    path('product/', include('product.urls')),
    path('account/', include('shop_user.urls')),
    path('question/', include('question.urls')),
    path('', include('custom.urls')),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('robots.txt/', lambda x: HttpResponse("User-Agent: *\nDisallow:",
         content_type="text/plain")),
    # path('admin/log_viewer/', include('log_viewer.urls')),
    # path("__reload__/", include("django_browser_reload.urls")),
    # path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pinot_shop/src/shop_management/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from . import views
urlpatterns = [
    path("", views.main),
    path("template", views.template),
    path("get_theme", views.get_theme),
    path("event", views.event),
    path("privacy", views.privacy),
    path("contract", views.contract),
    path("contact", views.contact),
    path("notice", views.notice),
    path("faq", views.faq),
    path("faq/<int:id>", views.faq_detail),
    path("event/detail/<int:id>", views.event_detail),
    path("notice/detail/<int:id>", views.notice_detail),
    path("partner", views.partner),
    path("get_zone", views.get_zone),
]

pinot_shop/src/shop_management/models.py
from pyexpat import model
from django.db import models
import datetime
from pytz import timezone as pytzone
# Create your models here.


class Notice(models.Model):
    thumbnail = models.FileField(upload_to="notice", blank=True, null=True)
    title = models.CharField(max_length=500)
    short_sub_title = models.CharField(max_length=600, blank=True, null=True)
    short = models.CharField(max_length=600, blank=True, null=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    view_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def previous_notice(self):
        current_id = self.id
        prev = Notice.objects.filter(id__lt=current_id).order_by("-id").first()
        if prev:
            return {"title": prev.title, "id": prev.id}
        else:
            return {"title": "이전글이 없습니다.", "id": ""}

    def next_notice(self):
        current_id = self.id
        next = Notice.objects.filter(id__gt=current_id).order_by("id").first()
        if next:
            return {"title": next.title, "id": next.id}
        else:
            return {"title": "다음글이 없습니다.", "id": ""}

    def thumbnail_url(self):
        if self.thumbnail:
            return self.thumbnail.url
        else:
            return ""


class Inquiry(models.Model):
    title = models.CharField(max_length=500)
    author = models.CharField(max_length=500)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    phone = models.CharField(max_length=500)
    email = models.CharField(max_length=500)
    attached_file = models.FileField(upload_to="inquiry")
    is_locked = models.BooleanField(default=True)
    password = models.CharField(max_length=500)


class InquiryReply(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class SiteManagement(models.Model):
    company_logo = models.ImageField()
    company_info = models.TextField()
    caution = models.TextField()
    delivery_info = models.TextField()
    welecome_point = models.IntegerField()
    puchase_point = models.IntegerField()
    personal_info_regulation = models.TextField()
    agreement_regulation = models.TextField()


class Jumbotron(models.Model):
    name = models.CharField(max_length=500, blank=True, null=True)
    wide_img = models.ImageField(upload_to="jumbotron")
    small_img = models.ImageField(upload_to="jumbotron")
    mobile_img = models.ImageField(
        upload_to="jumbotron", blank=True, null=True)
    index = models.IntegerField(default=0)
    link = models.CharField(max_length=500, blank=True, null=True)
    view_count = models.IntegerField(default=0)

    def wide_img_url(self):
        if self.wide_img:
            return self.wide_img.url
        else:
            return ""

    def small_img_url(self):
        if self.small_img:
            return self.small_img.url
        else:
            return ""

    def mobile_img_url(self):
        if self.mobile_img:
            return self.mobile_img.url
        else:
            return ""

    def recent_click_count(self):
        target_date = datetime.datetime.now(
            pytzone('Asia/Seoul')) - datetime.timedelta(30)

        return self.jb.filter(created_at__gt=target_date).count()


class JumbotronClickCount(models.Model):
    jumbotron = models.ForeignKey(
        Jumbotron, on_delete=models.CASCADE, verbose_name="점보트론", blank=True, null=True, related_name="jb")
    ua = models.CharField(max_length=500, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)


class Faq(models.Model):
    title = models.CharField(max_length=500)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    view_count = models.IntegerField(default=0)
    CATEGORY = (
        ("회원문의", "회원문의"),
        ("주문/결제", "주문/결제"),
        ("취소/교환/반품", "취소/교환/반품"),
        ("배송문의", "배송문의"),
        ("쿠폰/적립금", "쿠폰/적립금"),
        ("서비스 이용 및 기타", "서비스 이용 및 기타"),
    )
    category = models.CharField(
        choices=CATEGORY, max_length=30, blank=True, null=True)

    def __str__(self):
        return self.title

    def previous_faq(self):
        current_id = self.id
        prev = Faq.objects.filter(id__lt=current_id).order_by("-id").first()
        if prev:
            return {"title": prev.title, "id": prev.id}
        else:
            return {"title": "이전글이 없습니다.", "id": ""}

    def next_faq(self):
        current_id = self.id
        next = Faq.objects.filter(id__gt=current_id).order_by("id").first()
        if next:
            return {"title": next.title, "id": next.id}
        else:
            return {"title": "다음글이 없습니다.", "id": ""}


class PartnerInquiry(models.Model):
    company_name = models.CharField(max_length=100)
    manager_name = models.CharField(max_length=100)
    tel = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    title = models.CharField(max_length=300)
    contents = models.TextField()
    file = models.FileField(upload_to="partner_files/")
    created_at = models.DateTimeField(auto_now_add=True)

pinot_shop/src/shop_management/views.py
import math
from django.shortcuts import render
from product.models import *
from menu.models import *
from shop_management.models import *
from django.http import JsonResponse
from util import ecounterp
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.


def main(request):
    theme = Theme.objects.all()
    jumbotron = Jumbotron.objects.all().order_by("index")
    for jb in jumbotron:
        jb.view_count = jb.view_count+1
        jb.save()
    row_list = Category.objects.filter(parent_category=None)
    main_shortcut_list = MainShortcut.objects.all().order_by("index")
    return render(request, "shop_management/index.html",
                  {"main_shortcut_list": main_shortcut_list, "data": "data", "theme": theme, "row_list": row_list, "jumbotron": jumbotron})


def get_theme(request):
    theme_id = request.GET.get("id")
    product_list = ShopProduct.objects.filter(theme__id=theme_id)
    return render(request, "product/components/product.html", {"product_list": product_list})


def event(request):
    notices = Notice.objects.all().order_by("-id")
    return render(request, "shop_management/event.html", {"notices": notices})


def notice(request):
    per = request.GET.get("per")
    if per == "" or per == None:
        per = 20
    page = request.GET.get("page")
    if page == "" or page == None:
        page = 1
    per = int(per)
    page = int(page)
    total_page = math.ceil(Notice.objects.all().count() / per)
    notice_list = Notice.objects.all().order_by(
        "-created_at")[(page-1)*per:page*per]
    # if total_page == 1:

    return render(request, "shop_management/notice.html", {"notice_list": notice_list, "total_page": range(1, total_page+1)})


def notice_detail(request, id):

    notice = Notice.objects.get(id=id)
    notice.view_count = notice.view_count + 1
    notice.save()
    return render(request, "shop_management/notice_detail.html", {"notice": notice})


def faq(request):
    per = request.GET.get("per")
    if per == "" or per == None:
        per = 20
    page = request.GET.get("page")
    if page == "" or page == None:
        page = 1
    per = int(per)
    page = int(page)
    total_page = math.ceil(Faq.objects.all().count()/per)

    faq_list = Faq.objects.all().order_by("-created_at")[(page-1)*per:page*per]
    return render(request, "shop_management/faq.html", {"faq_list": faq_list, "total_page": range(1, total_page+1)})


def faq_detail(request, id):
    faq = Faq.objects.get(id=id)
    return render(request, "shop_management/faq_detail.html", {"faq": faq})


def privacy(request):
    return render(request, "shop_management/privacy.html")


def contract(request):
    return render(request, "shop_management/contract.html")


def contact(request):
    return render(request, "shop_management/contact.html")


def event_detail(request, id):
    notice = Notice.objects.get(id=id)
    return render(request, "shop_management/event_detail.html", {"notice": notice})


def template(request):
    return render(request, "shop_management/template.html")


def get_zone(request):
    ecounterp.write_order()
    # ecounterp.login()


def partner(request):
    if request.method == "GET":
        return render(request, "shop_management/partner.html",)
    else:
        print(request.FILES.get("file"))
        pi = PartnerInquiry()
        pi.company_name = request.POST.get("company_name")
        pi.manager_name = request.POST.get("manager_name")
        pi.tel = request.POST.get("tel")
        pi.email = request.POST.get("email")
        pi.title = request.POST.get("title")
        pi.contents = request.POST.get("contents")
        pi.file = request.FILES.get("file")
        pi.save()
        messages.info(request, '제휴 제안이 등록되었습니다. 검토후 연락드리겠습니다.')
        return HttpResponseRedirect('/')

pinot_shop/src/shop_management/templates/shop_management/company_base.html
{% extends "shop_management/base.html" %}
{% load sass_tags %}

{% block body %}
<link href="/static/css/custom_order.css" rel="stylesheet" type="text/css" />
<div class="container custom_order">
   <div   style="">     
      <section class="board_list" style="" >
         <div class="page_aticle aticle_type2">
            <div id="snb" class="snb_cc">
               <h2 class="tit_snb">고객센터</h2>
               <div class="inner_snb">
                  <ul class="list_menu">
                     <li {% if request.path == "/notice" %} class="on"{% endif%}>
                        <a href="/notice">공지사항</a>
                     </li>
                     <li {% if request.path == "/faq" %} class="on"{% endif%}>
                        <a href="/faq">자주하는질문</a>
                     </li>
                     <li {% if request.path == "/privacy" %} class="on"{% endif%}>
                        <a href="/privacy" >개인정보처리방침 </a>
                     </li>
                     <li {% if request.path == "/contract" %} class="on"{% endif%}>
                        <a href="/contract" >이용약관 </a>
                     </li>
                    <li {% if request.path == "/company" %} class="on"{% endif%}>
                        <a href="http://pinot.co.kr/" target="_blank" >회사소개 </a>
                     </li>
                  </ul>
               </div>
               {% comment %}     <a href="/partner" class="link_inquire"><span class="emph">도움이 필요하신가요 ?</span>제휴문의</a>
               {% endcomment %}
            </div>
            {% block content  %}           
            {% endblock %}
         </div>
      </section>
   </div>
</div>
<div style="clear:both"></div>
<style>
   .page_aticle.aticle_type2 {
      display:flex;
   }
   #snb {
   float: left;
   width: 200px;
   }
   #snb .tit_snb {
   padding: 8px 0 33px 1px;
   font-weight: 700;
   font-size: 30px;
   line-height: 34px;
   color: #333;
   letter-spacing: -.5px;
   }
   #snb .inner_snb {
   border: 1px solid #f2f2f2;
   border-bottom: 0;
   }
   #snb .list_menu li {
   border-bottom: 1px solid #f2f2f2;
   }
   #snb .list_menu li a {
   display: block;
   overflow: hidden;
   padding: 15px 0 15px 20px;
   background: #fff url(https://res.kurly.com/pc/ico/2008/ico_arrow_6x11.svg) no-repeat 174px 52%;
   background-size: 6px 11px;
   font-size: 14px;
   color: #666;
   line-height: 20px;
   letter-spacing: -.3px;
   }
   #snb .list_menu li.on a, #snb .list_menu li a:hover {
   background: #fafafa url(https://res.kurly.com/pc/ico/2008/ico_arrow_6x11_on.svg) no-repeat 174px 52%;
   background-size: 6px 11px;
   font-weight: 700;
   color: #5f0080;
   }
   #snb .link_inquire {
   display: block;
   overflow: hidden;
   width: 200px;
   height: 60px;
   margin-top: 20px;
   padding: 9px 0 0 21px;
   border-radius: 0 100px 100px 0;
   background: #fafafa url(https://res.kurly.com/pc/ico/2008/ico_arrow_6x11_on.svg) no-repeat 174px 25px;
   background-size: 6px 11px;
   font-size: 12px;
   color: #333;
   line-height: 20px;
   }
   #snb .link_inquire .emph {
   display: block;
   padding-bottom: 1px;
   font-weight: 700;
   font-size: 14px;
   }
   .page_aticle.aticle_type2 .page_section {
      width: calc(100% - 210px);
      margin-left: 10px;
   }
   .page_aticle .head_aticle {
   padding: 5px 0 34px;
   }
   .page_aticle .head_aticle .tit {
   height: 36px;
   font-weight: 700;
   font-size: 24px;
   line-height: 36px;
   color: #333;
   letter-spacing: -.5px;
   }
   .page_aticle .head_aticle .tit_sub {
   padding-left: 11px;
   font-size: 14px;
   color: #999;
   line-height: 20px;
   letter-spacing: -.3px;
   vertical-align: 3px;
   }
   .xans-myshop-couponserial {
   padding-bottom: 20px;
   }
   .xans-board-listheader.jh {
   border-bottom: 1px solid #f4f4f4;
   }
   .xans-board-listheader {
   border-top: 2px solid #522772;
   font-size: 13px;
   line-height: 140%;
   }
   .xans-board-listheader {
   font-size: 12px;
   }
   .xans-board-listheader th {
   padding: 20px 0;
   vertical-align: middle;
   font-size: 12px;
   }
   .xans-board-listheader tbody tr:first-child td {
   border-top: 1px solid #333;
   }
   .xans-board-listheader tbody tr:first-child td {
   border-top: 1px solid #333;
   }
   .xans-board-listheader tr td {
   padding: 12px;
   border-top: 1px solid #f4f4f4;
   text-align: center;
   vertical-align: middle;
   word-wrap: break-word;
   }
   .xans-board-listheader.jh tr td {
   padding: 20px 0;
   }
   .xans-board-listheader td a {
   color: #555;
   }
   .eng2 {
   color: #939393;
   }
   .page_aticle .layout-pagination {
   font-size: 0;
   }
   .page_aticle .layout-pagination-first-page:first-child {
   border-left: 1px solid #ddd;
   }
   .page_aticle .layout-pagination a {
   cursor: pointer;
   }
   .layout-pagination-prev-page {
   background-image: url(https://res.kurly.com/pc/etc/old/images/common/icon-pagination-prev.png);
   }
   .layout-pagination-first-page, .layout-pagination-prev-page, .layout-pagination-next-page, .layout-pagination-last-page {
   background-repeat: no-repeat;
   background-position: 50% 50%;
   text-indent: -9999px;
   }
   .layout-pagination-first-page {
   background-image: url(https://res.kurly.com/pc/etc/old/images/common/icon-pagination-first.png);
   }
   .layout-pagination-button {
   display: inline-block;
   width: 34px;
   height: 34px;
   border: 1px solid #ddd;
   border-left: 0;
   vertical-align: top;
   }
   .page_aticle .layout-pagination a, .page_aticle .layout-pagination strong {
   font-weight: 700;
   font-size: 12px;
   }
   .layout-pagination-number:hover, .layout-pagination-number.__active {
   background-color: #f7f7f7;
   color: #5f0080;
   }
   .layout-pagination-number {
   line-height: 34px;
   }
   .layout-pagination {
   margin: 60px 0 0;
   text-align: center;
   }
   .xans-board-search {
   margin-top: 30px;
   padding: 20px 0 20px 10px;
   color: #2e2e2e;
   font-size: 12px;
   clear: both;
   border-top: 1px solid #5e3d5a;
   width: 100%;
   }
   .xans-board-search2 {
   height: 80px;
   padding: 0;
   }
   .xans-board-search .input_txt img {
   position: relative;
   right: 5px;
   top: -2px;
   }
   .xans-board-search .stxt {
   font-size: 14px;
   }
   .xans-board-search .stxt input {
   margin-left: 10px;
   margin-right: 3px;
   position: relative;
   top: 3px;
   }
   .xans-board-search input[type=text] {
   height: 34px;
   line-height: 34px;
   width: 220px;
   border: 1px solid #bfbfbf;
   color: #000;
   float: right;
   padding: 4px;
   }
   .search_bt img {
   float: right;
   }
</style>


{% endblock %}

pinot_shop/src/shop_management/templates/shop_management/faq.html
{% extends "shop_management/company_base.html" %}

{% block content %}
      <form name="frmList" id="form" method="get" action="?" style="width: 100%;">
               <div class="page_section">
                  <div class="head_aticle">
                     <h2 class="tit">자주하는 질문 <span class="tit_sub">고객님들께서 가장 자주하시는 질문을 모두 모았습니다.</span></h2>
                  </div>
                  <div class="xans-element- xans-myshop xans-myshop-couponserial ">
                     <table width="100%" class="xans-board-listheader">
                        <tbody>
                           <tr>
                              <th width="70" class="input_txt">번호</th>
                              <th width="135" class="input_txt">카테고리</th>
                              <th class="input_txt">제목</th>
                           </tr>
                        </tbody>
                     </table>
                     <div>
                        {% for item in faq_list %}
                        <div>
                           <table width="100%" class="table_faq" onclick="location.href='/faq/{{item.id}}'" id="faq_7">
                              <tbody>
                                 <tr>
                                    <td width="70" align="center">{{item.id}}</td>
                                    <td width="135" align="center">{{item.get_category_display}}</td>
                                    <td style="cursor:pointer">{{item.title}}</td>
                                 </tr>
                              </tbody>
                           </table>                      
                        </div>
                        {% endfor %}
                     </div>
                     <div style="padding:1px; border-top:1px solid #e6e6e6"></div>
                     <div class="layout-pagination">
                        <div class="pagediv">
                           <a href="" style="border-left:1px solid #e6e6e6" class="layout-pagination-button layout-pagination-prev-page">이전 페이지로 가기</a>
                           
                           {% for item in total_page %}
                           <a href="/faq?page={{item}}" class="layout-pagination-button layout-pagination-number">{{item}}</a>
                           {% endfor %}
                           <a href="" class="layout-pagination-button layout-pagination-next-page">다음 페이지로 가기</a>
                           
                     </div>
                   
                  </div>
               </div>
            </form>
<style>
   th{
      text-align:center
   }
   .page_aticle.aticle_type2 {
  
   }
   #snb {
   float: left;
   width: 200px;
   }
   #snb .tit_snb {
   padding: 8px 0 33px 1px;
   font-weight: 700;
   font-size: 30px;
   line-height: 34px;
   color: #333;
   letter-spacing: -.5px;
   }
   #snb .inner_snb {
   border: 1px solid #f2f2f2;
   border-bottom: 0;
   }
   #snb .list_menu li {
   border-bottom: 1px solid #f2f2f2;
   }
   #snb .list_menu li a {
   display: block;
   overflow: hidden;
   padding: 15px 0 15px 20px;
   background: #fff url(https://res.kurly.com/pc/ico/2008/ico_arrow_6x11.svg) no-repeat 174px 52%;
   background-size: 6px 11px;
   font-size: 14px;
   color: #666;
   line-height: 20px;
   letter-spacing: -.3px;
   }
   #snb .list_menu li.on a, #snb .list_menu li a:hover {
   background: #fafafa url(https://res.kurly.com/pc/ico/2008/ico_arrow_6x11_on.svg) no-repeat 174px 52%;
   background-size: 6px 11px;
   font-weight: 700;
   color: #5f0080;
   }
   #snb .link_inquire {
   display: block;
   overflow: hidden;
   width: 200px;
   height: 60px;
   margin-top: 20px;
   padding: 9px 0 0 21px;
   border-radius: 0 100px 100px 0;
   background: #fafafa url(https://res.kurly.com/pc/ico/2008/ico_arrow_6x11_on.svg) no-repeat 174px 25px;
   background-size: 6px 11px;
   font-size: 12px;
   color: #333;
   line-height: 20px;
   }
   #snb .link_inquire .emph {
   display: block;
   padding-bottom: 1px;
   font-weight: 700;
   font-size: 14px;
   }
   .page_aticle.aticle_type2 .page_section {
      width: 100%!important;
      margin-left: 10px;
   }
   .page_aticle .head_aticle {
   padding: 5px 0 34px;
   }
   .page_aticle .head_aticle .tit {
   height: 36px;
   font-weight: 700;
   font-size: 24px;
   line-height: 36px;
   color: #333;
   letter-spacing: -.5px;
   }
   .page_aticle .head_aticle .tit_sub {
   padding-left: 11px;
   font-size: 14px;
   color: #999;
   line-height: 20px;
   letter-spacing: -.3px;
   vertical-align: 3px;
   }
   .xans-myshop-couponserial {
   padding-bottom: 20px;
   }
   .xans-board-listheader.jh {
   border-bottom: 1px solid #f4f4f4;
   }
   .xans-board-listheader {
   border-top: 2px solid #522772;
   font-size: 13px;
   line-height: 140%;
   }
   .xans-board-listheader {
   font-size: 12px;
   }
   .xans-board-listheader th {
   padding: 20px 0;
   vertical-align: middle;
   font-size: 12px;
   }
   .xans-board-listheader tbody tr:first-child td {
   border-top: 1px solid #333;
   }
   .xans-board-listheader tbody tr:first-child td {
   border-top: 1px solid #333;
   }
   .xans-board-listheader tr td {
   padding: 12px;
   border-top: 1px solid #f4f4f4;
   text-align: center;
   vertical-align: middle;
   word-wrap: break-word;
   }
   .xans-board-listheader.jh tr td {
   padding: 20px 0;
   }
   .xans-board-listheader td a {
   color: #555;
   }
   .eng2 {
   color: #939393;
   }
   .page_aticle .layout-pagination {
   font-size: 0;
   }
   .page_aticle .layout-pagination-first-page:first-child {
   border-left: 1px solid #ddd;
   }
   .page_aticle .layout-pagination a {
   cursor: pointer;
   }
   .layout-pagination-prev-page {
   background-image: url(https://res.kurly.com/pc/etc/old/images/common/icon-pagination-prev.png);
   }
   .layout-pagination-first-page, .layout-pagination-prev-page, .layout-pagination-next-page, .layout-pagination-last-page {
   background-repeat: no-repeat;
   background-position: 50% 50%;
   text-indent: -9999px;
   }
   .layout-pagination-first-page {
   background-image: url(https://res.kurly.com/pc/etc/old/images/common/icon-pagination-first.png);
   }
   .layout-pagination-button {
   display: inline-block;
   width: 34px;
   height: 34px;
   border: 1px solid #ddd;
   border-left: 0;
   vertical-align: top;
   }
   .page_aticle .layout-pagination a, .page_aticle .layout-pagination strong {
   font-weight: 700;
   font-size: 12px;
   }
   .layout-pagination-number:hover, .layout-pagination-number.__active {
   background-color: #f7f7f7;
   color: #5f0080;
   }
   .layout-pagination-number {
   line-height: 34px;
   }
   .layout-pagination {
   margin: 60px 0 0;
   text-align: center;
   }
   .xans-board-search {
   margin-top: 30px;
   padding: 20px 0 20px 10px;
   color: #2e2e2e;
   font-size: 12px;
   clear: both;
   border-top: 1px solid #5e3d5a;
   width: 100%;
   }
   .xans-board-search2 {
   height: 80px;
   padding: 0;
   }
   .xans-board-search .input_txt img {
   position: relative;
   right: 5px;
   top: -2px;
   }
   .xans-board-search .stxt {
   font-size: 14px;
   }
   .xans-board-search .stxt input {
   margin-left: 10px;
   margin-right: 3px;
   position: relative;
   top: 3px;
   }
   .xans-board-search input[type=text] {
   height: 34px;
   line-height: 34px;
   width: 220px;
   border: 1px solid #bfbfbf;
   color: #000;
   float: right;
   padding: 4px;
   }
   .search_bt img {
   float: right;
   }
   .search_date {
   position: relative;
   z-index: 1;
   }
   .search_date .layer_search {
   display: none;
   position: absolute;
   right: 0;
   top: -30px;
   width: 157px;
   border: 1px solid #dddfe1;
   border-top: 0;
   }
   .search_date .layer_search li {
   background-color: #fff;
   border-top: 1px solid #dddfe1;
   }
   .search_date .layer_search li:first-child {
   border-top: 0;
   }
   .search_date .layer_search a {
   display: block;
   overflow: hidden;
   height: 32px;
   padding: 7px 0 0 8px;
   font-size: 12px;
   color: #666;
   line-height: 18px;
   letter-spacing: -.2px;
   }
   .search_date .btn_layer {
   overflow: hidden;
   position: absolute;
   right: 0;
   top: -74px;
   width: 157px;
   height: 44px;
   padding: 11px 0 0 15px;
   border: 1px solid #ddd;
   font-size: 14px;
   color: #666;
   line-height: 18px;
   letter-spacing: -.5px;
   }
   .search_date .btn_layer:after {
   content: "";
   position: absolute;
   left: 128px;
   top: 18px;
   width: 12px;
   height: 8px;
   background: url(https://res.kurly.com/pc/ico/2008/ico_down_12x8.svg) no-repeat 0 0;
   background-size: 12px 8px;
   }
   .table_faq tr td {
   padding: 20px 0;
   }   
   .table_faq tr td  {
   font-size: 12px;
   }
   .table_faq {
   border-top: 1px solid #f4f4f4;
   }
   .xans-board-search input[type=image] {
   float: right;
   position: relative;
   }
   .layout-pagination-next-page {
   background-image: url(https://res.kurly.com/pc/etc/old/images/common/icon-pagination-next.png);
   }
   .layout-pagination-last-page {
   background-image: url(https://res.kurly.com/pc/etc/old/images/common/icon-pagination-last.png);
   }
</style>
{% endblock %}