pinot_shop/src/menu/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/menu/', views.admin_menu, name="menu_admin"),
]

pinot_shop/src/pino_acryl/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.http import HttpResponse

urlpatterns = [
    path('', include('menu.urls')),
    path('', include('shop_management.urls')),
    path('shop_admin/', include('shop_admin.urls')),
    path('sample_image/', include('sample_image.urls')),
    path('product/', include('product.urls')),
    path('account/', include('shop_user.urls')),
    path('question/', include('question.urls')),
    path('', include('custom.urls')),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('robots.txt/', lambda x: HttpResponse("User-Agent: *\nDisallow:",
         content_type="text/plain")),
    # path('admin/log_viewer/', include('log_viewer.urls')),
    # path("__reload__/", include("django_browser_reload.urls")),
    # path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pinot_shop/src/product/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('banner_click/<int:id>', views.banner_click),
    path('list/<int:id>', views.list),
    path('all/<int:id>', views.all),
    path('all', views.all),
    path('select', views.select),
    path('estimate/<str:id>', views.estimate),
    path('search', views.search),
    path('detail/<int:id>', views.detail),
    path("get_delievery_type", views.get_delievery_type),
]

pinot_shop/src/product/models.py
from django.db import models

# Create your models here.


class ShopProduct(models.Model):
    category = models.ForeignKey(
        "menu.Category", blank=True, null=True, on_delete=models.SET_NULL, verbose_name="상품 카테고리")
    name = models.CharField(max_length=500, verbose_name="상품 이름")
    description_summary = models.TextField(verbose_name="상품 간단 소개")
    showing_price = models.IntegerField(
        default=0, verbose_name="상품 원래 가격(리스트 노출)")
    detail = models.TextField(verbose_name="상품 상세 정보")
    created_at = models.DateTimeField(auto_now_add=True)
    is_hot = models.BooleanField(default=False)
    is_new = models.BooleanField(default=False)
    discount_price = models.IntegerField(
        default="0", verbose_name="상품 할인가격", blank=True, null=True, max_length=20)
    count_convention = models.CharField(
        default="", verbose_name="상품 판매단위", blank=True, null=True, max_length=20)
    selling_range = models.CharField(
        default="", verbose_name="상품 판매범위", blank=True, null=True, max_length=20)
    theme = models.ManyToManyField("Theme", blank=True,  verbose_name="상품 테마")
    option_json_data = models.TextField(
        verbose_name="상품 옵션 json 데이터 ", blank=True, null=True)
    additional_product_json_data = models.TextField(
        verbose_name="상품 옵션 json 데이터 ", blank=True, null=True)
    point = models.IntegerField(default=0, verbose_name="상품 포인트")
    delivery_duration = models.CharField(max_length=30, blank=True, null=True)
    need_to_file_upload = models.BooleanField(default=False)
    direct_receive_price = models.IntegerField(
        default=0, verbose_name="방문수령 가격")
    pre_parcel_price = models.IntegerField(
        default=0, verbose_name="선불택배 수령 가격")
    after_parcel_price = models.IntegerField(
        default=0, verbose_name="후불택배 수령 가격")
    pre_quick_price = models.IntegerField(default=0, verbose_name="선불퀵 수령 가격")
    after_quick_price = models.IntegerField(
        default=0, verbose_name="후불퀵 수령 가격")
    pre_carton_price = models.IntegerField(
        default=0, verbose_name="선불 화물 수령 가격")
    after_carton_price = models.IntegerField(
        default=0, verbose_name="후불 화물 수령 가격")
    local_delivery_price = models.IntegerField(
        default=0, verbose_name="지역배송 가격")
    self_delivery = models.IntegerField(default=0, verbose_name="방문수령 가격")
    is_show = models.BooleanField(default=True)
    is_main_display = models.BooleanField(default=False)
    sell_count = models.IntegerField(default=0)  # 판매량
    view_count = models.IntegerField(default=0)  # 판매량
    template_file = models.CharField(max_length=1000, blank=True, null=True)
    show_index = models.IntegerField(default=0)  # 보이는 순서

    group = models.ForeignKey("ShopProductGroup", blank=True, null=True, verbose_name="상품 그룹", on_delete=models.SET_NULL)
    group_specific_name = models.CharField(max_length=1000, blank=True, null=True)
    group_specific_index = models.IntegerField(default=0)
    is_group_main_product = models.BooleanField(default=False)
    def __str__(self):
        return self.name

    def image_url(self):
        img = ShopProductImage.objects.filter(product=self.id).order_by("index").first().image.url
        return img
    class Meta:
        ordering = ['-id']


class ShopProductGroup(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)
    def __str__(self):
        return self.name

    def group_product_set_id_list(self):
        return list(ShopProduct.objects.filter(group=self).order_by("group_specific_index").values("id","group_specific_name"))
    def product_set(self):
        return ShopProduct.objects.filter(group=self).order_by("-show_index")
        

class ShopProductImage(models.Model):
    product = models.ForeignKey(
        ShopProduct, on_delete=models.CASCADE, verbose_name="상품", blank=True, null=True)
    image = models.ImageField(
        upload_to="product/%Y/%m/%d/", verbose_name="상품이미지")
    index = models.IntegerField(default=0)

    class Meta:
        ordering = ['index']


class Theme(models.Model):
    name = models.CharField(max_length=100, verbose_name="상품 테마")

    def __str__(self):
        return self.name


class DelieveryType(models.Model):
    DELIVER_CHOICES = (
        ("선불", "선불"),
        ("후불", "후불"),
    )
    delievery_type = models.CharField(
        max_length=10, choices=DELIVER_CHOICES, blank=True, null=True)
    text = models.CharField(max_length=100, blank=True, null=True)
    price = models.IntegerField(default=0)

    def get_name(self):
        return self.name+":"+str(self.price)


class TempFile(models.Model):
    temp_file = models.FileField(blank=True, null=True, verbose_name="임시 파일")

pinot_shop/src/product/views.py
from datetime import datetime
from django.shortcuts import render
from .models import *
from menu.models import *
from review.models import *
from question.models import *
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q, F
import json
from django.core import mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from sample_image.models import *
# Create your views here.

def all(request, id=0):
    parent_id = ""
    current_main_category = ""
    if(id==0):
        category= Category.objects.filter( parent_category__isnull=False).order_by("index")
        total_category_id_list = Category.objects.all().values_list("id")

    else:
        category = Category.objects.get(id=id)
        if category.parent_category:
            parent_id = category.parent_category.id
        total_category_id_list = []
        total_category_id_list.append(id)
        for item in category.category_set.all():
            total_category_id_list.append(item.id)
    main_category = Category.objects.filter(
        parent_category=None).order_by("index")
    if parent_id:
        current_main_category = Category.objects.get(id=parent_id)
    elif id != 0:
        current_main_category = Category.objects.get(id=id)

    page = int(request.GET.get("page")) if request.GET.get("page") else 1
    per_count = int(request.GET.get("count")
                    ) if request.GET.get("count") else 20
    order_by = request.GET.get("order_by") if request.GET.get("order_by") else "-show_index"
    print(order_by)


    included_product = ShopProduct.objects.filter(category__in=total_category_id_list).filter(is_show=True).order_by(
        order_by)[(page - 1) * per_count: page * per_count]
    all_product_length = ShopProduct.objects.filter(category__in=total_category_id_list).filter(is_show=True).count()
    image_id = request.GET.get("image_id")
    product_id = request.GET.get("product_id")
    image = ""
    if image_id :
        image = SampleImage.objects.get(id=image_id)
    product=""
    if product_id :
        product = ShopProduct.objects.get(id=product_id)

    return render(request, "product/all.html", {
        "current_main_category":current_main_category,
        "parent_id":parent_id,
        "id":id,
        "category": category,
        "included_product": included_product,
        "main_category": main_category,
        "id": id,
        "order_by": order_by,
        "page": page,
        "per_count": per_count,
        "product_id":product_id,
        "product":product,
        "image_id": image_id, "image": image,
        "all_product_length": all_product_length
    })


def list(request, id=1):
    category = Category.objects.get(id=id)
    total_category_id_list = []
    total_category_id_list.append(id)
    main_category = Category.objects.filter(
        parent_category=None).order_by("index")

    page = int(request.GET.get("page")) if request.GET.get("page") else 1
    per_count = int(request.GET.get("count")
                    ) if request.GET.get("count") else 20
    order_by = request.GET.get("order_by") if request.GET.get("order_by") else "-show_index"
    print(order_by)
    for item in category.category_set.all():
        total_category_id_list.append(item.id)

    included_product = ShopProduct.objects.filter(category__in=total_category_id_list).filter(is_show=True).order_by(
        order_by)[(page-1)*per_count: page*per_count]
    image_id = request.GET.get("image_id")
    image = ""
    if image_id:
        image = SampleImage.objects.get(id=image_id)
    return render(request, "product/list.html", {
        "category": category,
        "included_product": included_product,
        "main_category": main_category,
        "id": id,
        "order_by": order_by,
        "page": page,
        "per_count": per_count,
        "image_id":image_id,"image":image
    })


def search(request, id=1):
    keyword = request.GET.get("q")
    included_product = ShopProduct.objects.filter(
        Q(name__icontains=keyword) | Q(description_summary__icontains=keyword))
    search_banner = Banner.objects.filter(type="search").first()
    return render(request, "product/search.html", {"included_product": included_product, "id": id, "search_banner": search_banner})


@csrf_exempt
def detail(request, id=1):

    if request.method == "POST":
        # 문의 내용 남기기
        Question(
            author=request.user,
            name=request.user.nickname,
            product_id=request.POST.get("id"),
            content=request.POST.get("content"),
            title=request.POST.get("title"),
        ).save()
        return JsonResponse({"result": "ok"})
    else:
        image_id = request.GET.get("image_id")
        product = ShopProduct.objects.get(id=id)
        ShopProduct.objects.filter(id=id).update(view_count=F('view_count')+1)
        qna = Question.objects.filter(product_id=id).order_by("-created_at")
        if product.additional_product_json_data != None:
            additional_product = json.loads(product.additional_product_json_data)[
                "additional_product"]
        else:
            additional_product = []
        return render(request, "product/detail.html", {"image_id":image_id,"product": product, "qna": qna, "additional_product": additional_product})


def get_delievery_type(request):
    delievery_type = DelieveryType.objects.all().values()
    return JsonResponse({"result": list(delievery_type)})


@csrf_exempt
def estimate(request, id="1"):
    if request.method == "GET":
        id = id.split(",")
        basket_product = Basket.objects.filter(id__in=id)
        return render(request, "product/estimate.html", {"basket_product": basket_product})
    else:
        htmly = request.POST.get("html")
        str_format = str(datetime.now().year)+"년 " + \
            str(datetime.now().month)+"월 " + str(datetime.now().day)+"일 "
        print(str_format)
        mail.send_mail("[피노마켓] " + str_format + " 견적서를 전달드립니다.", strip_tags(htmly),
                       ' pinot <market@pinotmarket.co.kr>', [request.POST.get("email")], html_message=htmly)
        return JsonResponse({"RESULT": "OK"})


@csrf_exempt
def banner_click(request, id=1):
    Banner.objects.filter(id=id).update(click_count=F('click_count')+1)
    return JsonResponse({"result": "OK"})



def select(request, id=0):

  
    image_id = request.GET.get("image_id")
    product_id = request.GET.get("product_id")
    image = ""
    if image_id :
        image = SampleImage.objects.get(id=image_id)
    product=""
    if product_id :
        product = ShopProduct.objects.get(id=product_id)

    return render(request, "product/select.html", {
        "id":id,    
        "id": id,      
        "product_id":product_id,
        "product":product,
        "image_id": image_id, "image": image,     
    })

pinot_shop/src/product/templates/product/components/design_print_option.html
{% load product_options %} {% load humanize %}
<div class="print_option product_option_item">
  <span class="option_title"
    >인쇄
    <span
      onclick="document.querySelector('.print_option').scrollIntoView({behavior: 'smooth'});"
    >
      <i data-pointer-class="print_option" class="las la-question-circle pointer"></i>
    </span>
  </span>
  <select class="select_form" name="print">
    <option data-name="none" value="0">미선택</option>
    {% for item in product|get_print_option_list:"인쇄 옵션" %}
    <option data-name="{{item.name}}" value="{{item.price}}"
      >{{item.name}} {% if item.price != 0 %} (+{{item.price|intcomma}}원)
       {% endif %}</option
    >
    {% endfor %}
  </select>
</div>
<div class="design_select product_option_item" style="display: none">
  <span class="option_title"
    >디자인
    <span
      onclick="document.querySelector('.print_option').scrollIntoView({behavior: 'smooth'});"
    >
      <i data-pointer-class="print_option" class="las la-question-circle"></i></span
  ></span>
  <select class="select_form" name="design">
    <option value="0">완성데이터</option>
    <option value="5000">디자인 요청(수정) (+5,000원) </option>
    <option value="10000">디자인 요청(신규제작) (+10,000원)</option>
  </select>
</div>

pinot_shop/src/product/templates/product/components/product.html
{% load humanize %}
{% load product_options %}
<style>
    .group .select_product{
        display: none;
    }
    .group:hover .select_product{
        display: block!important;
    }
</style>
{% for item in product_list %}

  <a class="inline-block w-full relative"
   {%  if "all" in request.path %}
      href="/product/select?image_id={{ image_id|default:"" }}&product_id={{ item.id }}"
          {% else %}
     href="/product/detail/{{item.id}}?image_id={{ image_id }}"
        {% endif %}
  >


    <div class="group w-full   mt-3 border-slate-100 hover:cursor-pointer">
      {%  if "all" in request.path %}
      <button  class="btn btn-primary select_product  group-hover:inline-block " style="position: absolute;transform: translate(-50%,-50%);top:50%;left:50%;z-index: 999">
          제품 선택하기</button>
    {% endif %}
      <div class=" w-full aspect-square  mb-3 overflow-hidden relative" style="padding-bottom:100%; ">
        <img style="width:100%;" class=" absolute transition-all aspect-square hover:scale-110 " src="{{item.shopproductimage_set.all.0.image.url}}" alt="상품"/>
        <div style="position:absolute;bottom:0px; display:flex; justify-content:end; width: 100%;">
          {% if item.is_new %}
          <div class="new" style="padding: 3px 5px; background-color:green; color:#fff">NEW</div>
          {% endif %}
          {% if item.is_hot %}
          <div class="hot" style="padding: 3px 5px; background-color:red; color:#fff">HOT</div>
          {% endif %}
        </div>
      </div>
      <div class="name   font-semibold text-lg text-neutral-500 group-hover:text-neutral-800 " style="word-break: keep-all">
        {{item.name}}
      </div>
      <div class="description text-sm text-neutral-600 min-h-[40px]" style="margin-top:10px">
        {{item.description_summary}}&nbsp;
      </div>
        <div class="price  mb-3 pt-2">
            {% is_same_price item as result %}
            {% if not result %}
              <span class="percent  text-red-700  text-lg  font-bold">
                {% get_product_discount_sale item %}%
              </span>
              <span class="inline-block ml-1 text-gray-500 font-semibold text-sm mr-3 " style="text-decoration: line-through">
                {{item.showing_price|intcomma}}원
              </span>
            {% endif %}
            <div class="relative inline-block font-semibold  text-gray-900 text-lg ">
              {{item.discount_price|intcomma}}원 ~
              <div class="transition-all absolute bottom-0 right-0 w-0 border border-red-400 opacity-0 group-hover:w-full group-hover:opacity-90"></div>
            </div>
        </div>
    </div>
  </a>
{% endfor %}

pinot_shop/src/product/templates/product/components/product_qna.html
<!-- qna 목록이 있는 경우  -->
<div class="info_contents qna qna_list">
{% if qna  %}
    {% for item in qna %}
     <article class="qna_item">
        <div class="row">
            <div class=" qna_text col-9" style="width: 800px;">
                <ul>
                    <li class="qna_title text_title cursor-pointer">{{item.title}}</li>
                    <li class="qna_summary text_content  cursor-pointer">{{item.content|truncatechars:30}}</li>
                    <li class="qna_origin text_content  hidden">{{item.content|linebreaksbr}}</li>
                </ul>
            </div>
            <div class="qna_text col-3">
                <ul>
                    <li class="text_writer">작성자:<span class="text inline-block ">
                    {% if item.author %}
                        {{item.author.nickname}}
                    {%else%}
                        {{item.name}}
                    {% endif %}
                    </span>
                    {% if item.author %}
                        {% if item.author == user %} <span data-id="{{ item.id }}" class="text-red-700 cursor-pointer qna_delete">삭제</span> {% endif %}
                    {% endif %}
                    </li>
                    <li class="text_date">등록일: <span class="text">{{item.created_at | date:"Y.m.d"}}</span></li>
                </ul>
            </div>
        </div>
    </article>
    {% endfor %}
    <div class="pagination"></div>
{% else %}

<!-- 상품 문의가 없는 경우 -->
    <article>
        <div class="row" style="font-size: 20px; line-height: 30px; text-align:center;padding: 20px 0px;justify-content: center;">
            상품 문의가 없습니다.
        </div>
    </article>
{% endif %}
    <article>
        <div class="row" style="font-size: 20px; line-height: 30px; text-align:center; width: 100%;margin-left:0px;  ">
            <div class="col-12 relative pl-0" style="padding-right: 0px; ">
                <input class="text-base" id="qna_title" style="width: 100%;margin-top: 10px;height: 39px;border-bottom: 1px solid #ddd ; padding-left: 10px;color:#333;" placeholder="문의 제목을 입력해주세요.">
                <textarea class="text-base mt-1" id="qna_content" style="width: 100%; background-color:rgba(250,250,250); height: 100px;  border: 1px solid #ddd; color:#333; padding: 10px;" placeholder="문의 내용을 입력해주세요"></textarea>
                <button id="qna_submit" class="product_qna_submit text-sm rounded-full bg-gray-500 text-white py-1 px-3 absolute right-0 top-3">문의 하기</button>
            </div>
        </div>
    </article>
</div>

pinot_shop/src/product/templates/product/components/product_zoom_image.html
<div class="img_container">
    <div class="main cover_img xxs:w-full xxs:aspect-square "
        style="aspect-ratio: 1/1;background-image:url({{product.shopproductimage_set.all.0.image.url}});position:relative;background-size:contain;background-repeat: no-repeat;background-position: center;"
    >
    <div id="zooming_window" style="background-repeat:no-repeat; background-color: #fff;;    pointer-events: none;border: 1px solid #ddd;width: 200px; height: 200px; position: absolute; z-index:2000; display: none;"></div>
    </div>
    <div class="img_con" style="flex-wrap:wrap">
        {% for item in product.shopproductimage_set.all %}
        <div class="thumb_img w-[calc(20%-8px)] aspect-square"
        style="background-image:url({{item.image.url}}); background-size: 100% ; background-position: center;padding-bottom:calc(20% - 8px);margin-bottom: 10px"
        ></div>
       {% endfor %}
    </div>
</div>
<style>
    .thumb_img:nth-child(5n){
        margin-right: 0px!important;
    }
</style>