pinot_shop/src/menu/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/menu/', views.admin_menu, name="menu_admin"),
]

pinot_shop/src/pino_acryl/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.http import HttpResponse

urlpatterns = [
    path('', include('menu.urls')),
    path('', include('shop_management.urls')),
    path('shop_admin/', include('shop_admin.urls')),
    path('sample_image/', include('sample_image.urls')),
    path('product/', include('product.urls')),
    path('account/', include('shop_user.urls')),
    path('question/', include('question.urls')),
    path('', include('custom.urls')),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('robots.txt/', lambda x: HttpResponse("User-Agent: *\nDisallow:",
         content_type="text/plain")),
    # path('admin/log_viewer/', include('log_viewer.urls')),
    # path("__reload__/", include("django_browser_reload.urls")),
    # path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pinot_shop/src/shop_admin/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("", views.index),
    path("complete", views.complete),
    path("modify_project", views.modify_project),
    path("modify_receipt", views.modify_receipt),
    path("get_project", views.get_project),
    path("delete_project", views.delete_project),
    path("ajax_project", views.ajax_project),
    path("login", views.admin_login),
    path("user_list", views.user_list),
    path("abuser_list", views.abuser_list),
    path("user_list/add", views.add_user),
    path("user_detail", views.user_detail),
    path("inquiry", views.inquiry),
    path("review", views.review),
    path("add_order", views.add_order),
    path("order", views.order),
    path("order_history", views.order_history),
    path("ajax_order", views.ajax_order),
    path("delivery_list", views.delivery_list),
    path("confirm", views.confirm),
    path("waiting", views.waiting),
    path("cancel", views.cancel),
    path("refund", views.refund),
    path("change", views.change),
    path("deto", views.deto),
    path("add_product", views.add_product),
    path("modify_product/<int:id>", views.modify_product),
    path("product_list", views.product_list),
    path("notice_list", views.notice_list),
    path("specification_sheet", views.specification_sheet),
    path("add_specification_sheet", views.add_specification_sheet),
    path("ajax_notice/<int:id>", views.ajax_notice),
    path("ajax_notice", views.ajax_notice),
    path("internal/employee", views.employee_list),
    path("internal/ajax_employee", views.ajax_employee),
    path("custom_purchase", views.custom_purchase),
    path("change_product_index", views.change_product_index),
    path("custom_purchase_history", views.custom_purchase_history),
    path("custom_purchase_detail/<int:id>", views.custom_purchase_detail),
    path("custom_purchase_detail", views.custom_purchase_detail),
    path("get_category_data", views.get_category_data),
    path("upload_product_img", views.upload_product_img),
    path("get_product_img/<int:id>", views.get_product_img),
    path("jumbotron_list", views.jumbotron_list),
    path("jumbotron_click/<int:id>", views.jumbotron_click),
    path("main_shortcut_list", views.main_shortcut_list),
    path("main_shortcut_click/<int:id>", views.main_shortcut_click),
    path("custom_inpuiry", views.custom_inpuiry),
    path("ajax_custom_inquiry/<int:id>", views.ajax_custom_inquiry),
    path("ajax_custom_inquiry_answer/<int:id>",
         views.ajax_custom_inquiry_answer),
    path("ajax_design_custom/<int:id>", views.ajax_design_custom),
    path("ajax_design_custom", views.ajax_design_custom),
    path("ajax_design_custom_list/<int:id>", views.ajax_design_custom_list),
    path("partner", views.partner_inquiry_list),
    path("faq_list", views.faq_list),
    path("category_list", views.category_list),
    path("category_detail/<int:id>", views.category_detail),
    path("ajax_faq/<int:id>", views.ajax_faq),
    path("ajax_faq/", views.ajax_faq),
    path("banner_list", views.banner_list),
    path("dev/log", views.dev_log),
    path("dev/access_log", views.access_log),
    path("design_list", views.design_list),
    path("ajax_order_status", views.ajax_order_status),
    path("", views.index),
    path("upload_product_template_file", views.upload_product_template_file),
    path("purchase_design_item/<int:id>", views.purchase_design_item),
    path("change_deliver/<int:id>", views.change_deliver),
    path("product_group", views.product_group),
    path("product_group/<int:id>", views.product_group),
    path("sample_image_bulk_upload", views.sample_image_bulk_upload),
    path('sample_image_list', views.image_list),
    path('sample_image_list/<int:id>', views.image_list),
]

pinot_shop/src/menu/models.py
from django.db import models
from product.models import *
import datetime
from pytz import timezone as pytzone


class Category(models.Model):
    parent_category = models.ForeignKey(
        "Category", blank=True, null=True, on_delete=models.CASCADE, verbose_name="부모 카테고리")
    name = models.CharField(max_length=100, blank=True,
                            null=True, verbose_name="카테고리 이름")
    icon = models.CharField(max_length=100, blank=True,
                            null=True, verbose_name="카테고리 아이콘")
    thumbnail = models.ImageField(
        blank=True, null=True, verbose_name="카테고리 이미지")
    is_public = models.BooleanField(default=True)
    index = models.IntegerField(default=0)
    list_thumbnail = models.ImageField(
        blank=True, null=True, verbose_name="카테고리 리스트 페이지 이미지")

    class Meta:
        ordering = ['parent_category_id', "index"]

    def __str__(self):
        if self.parent_category:
            return self.parent_category.name + ">" + self.name
        else:
            return self.name

    def html_name(self):
        if self.parent_category:
            return self.parent_category.name + "  >  " + self.name
        else:
            return self.name

    @property
    def image_url(self):
        if self.thumbnail and hasattr(self.thumbnail, 'url'):
            return self.thumbnail.url
        else:
            return ""

    def list_thumbnail_url(self):
        if self.list_thumbnail and hasattr(self.list_thumbnail, 'url'):
            return self.list_thumbnail.url
        else:
            return ""

    @property
    def child_product(self):
        id_list = Category.objects.filter(
            parent_category=self).values_list("id")
        product_list = ShopProduct.objects.filter(category_id__in=id_list)
        return product_list[0:5]

    @property
    def main_display_product(self):
        product_list = ShopProduct.objects.filter(
            category__parent_category_id=self.id).filter(is_main_display=True).filter(is_show=True)
        return product_list[0:8]

    @property
    def product_count(self):
        if self.category_set.all().count() > 0:
            id_list = []
            for item in self.category_set.all():
                for product in item.shopproduct_set.all().filter(is_show=True):
                    id_list.append(product.id)
            return len(set(id_list))
        else:
            return len(self.shopproduct_set.all().filter(is_show=True))


class Banner(models.Model):
    BANNER_TYPE = (
        ("common", "전체 페이지(상단)"),
        ("category", "각 카테고리페이지"),
    )
    type = models.CharField(choices=BANNER_TYPE,
                            max_length=20, blank=True, null=True)
    category = models.ForeignKey(
        "Category", blank=True, null=True, on_delete=models.CASCADE)
    pc_image = models.FileField(upload_to="banner", blank=True, null=True)
    mobile_image = models.FileField(upload_to="banner", blank=True, null=True)
    name = models.CharField(max_length=30, blank=True, null=True)
    link = models.CharField(max_length=100, blank=True, null=True)
    background_color = models.CharField(max_length=30, blank=True, null=True)
    start_dt = models.DateField(blank=True, null=True)
    end_dt = models.DateField(blank=True, null=True)
    click_count = models.IntegerField(default=0)
    view_count = models.IntegerField(default=0)

    def pc_image_url(self):
        if self.pc_image:
            if self.start_dt is not None and self.end_dt is not None:
                if datetime.date.today() >= self.start_dt and datetime.date.today() <= self.end_dt:
                    return self.pc_image.url
                else:
                    return ""
            else:
                return ""
        else:
            return ""

    def mobile_image_url(self):
        if self.mobile_image:
            return self.mobile_image.url
        else:
            return ""


class MainShortcut(models.Model):
    pc_image = models.FileField(
        upload_to="main_shortcut", blank=True, null=True)
    mobile_image = models.FileField(
        upload_to="main_shortcut", blank=True, null=True)
    name = models.CharField(max_length=30, blank=True, null=True)
    link = models.CharField(max_length=100, blank=True, null=True)
    index = models.IntegerField(default=0)
    is_margin_top_exist = models.BooleanField()

    def pc_image_url(self):
        if self.pc_image:
            return self.pc_image.url
        else:
            return ""

    def mobile_image_url(self):
        if self.mobile_image:
            return self.mobile_image.url
        else:
            return ""

    def recent_click_count(self):
        target_date = datetime.datetime.now(
            pytzone('Asia/Seoul')) - datetime.timedelta(30)

        return self.sc.filter(created_at__gt=target_date).count()


class MainShortcutClickCount(models.Model):
    shortcut = models.ForeignKey(
        MainShortcut, on_delete=models.CASCADE, verbose_name="메인 숏컷", blank=True, null=True, related_name="sc")
    ua = models.CharField(max_length=500, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

pinot_shop/src/order/models.py
from django.contrib import admin
from .models import *
from django_json_widget.widgets import JSONEditorWidget
from django.contrib.postgres import fields
from prettyjson import PrettyJSONWidget
from django import forms
from django.db import models
from product.models import *
from shop_user.models import *

# Register your models here.


class Order(models.Model):
    ORDER_TYPE = (
        ("default", "주문 결제"),
        ("personal", "개인 결제")
    )
    order_type = models.CharField(choices=ORDER_TYPE, max_length=100)
    orderer = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(blank=True, null=True)
    phone = models.CharField(max_length=100, blank=True, null=True)
    address_simple = models.CharField(max_length=300)
    address_detail = models.CharField(max_length=300)
    postal_code = models.CharField(max_length=100)
    ORDER_STATE = (
        ("cancel", "취소"),
        ("before-purchase", "결제 대기중"),
        ("pending", "배송 준비중"),
        ("delievering", "배송중"),
        ("complete", "배송완료"),
        ("refund-delievering", "환불-배송중"),
        ("refund-complete", "환불완료"),
        ("changing-delievering", "교환-배송중"),
        ("changing-complete", "교환완료")
    )
    status = models.CharField(choices=ORDER_STATE, max_length=100)
    used_point = models.IntegerField(default=0)
    total_price = models.IntegerField(default=0)
    iamport_id = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    custom_purchase = models.ForeignKey(
        "CustomPurchase", on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        if self.iamport_id is not None:
            return self.iamport_id
        else:
            return "개인 결제"


class OrderedProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    order_product_detail = models.JSONField()
    delievery_type = models.CharField(max_length=30, blank=True, null=True)

    def __str__(self):
        return "주문제품"

    def get_product_name(self):
        id = self.order_product_detail["original_product_id"]
        return ShopProduct.objects.get(id=id).name


class Refund(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True)
    date = models.DateField(verbose_name="환불날짜",  auto_now_add=True)
    title = models.CharField(verbose_name="환불사유", max_length=200)
    price = models.IntegerField(verbose_name="공급가액")
    vat = models.IntegerField(verbose_name="부가세액")
    total = models.IntegerField(verbose_name="합계금액")


class CustomPurchase(models.Model):

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(verbose_name="개인 결제 이름", max_length=200)
    PURCHASE_STATE = (
        ("before-purchase", "결제 대기중"),
        ("before-send", "입금대기/확인중"),
        ("purchased", "결제완료"),
        ("creating", "제작중"),
        ("delievering", "배송중"),
        ("complete", "배송완료"),
    )
    thumbnail = models.ImageField(
        upload_to="custom_thumbnail/", blank=True, null=True)
    purchase_status = models.CharField(
        choices=PURCHASE_STATE, blank=True, null=True, max_length=30, default="before-purchase")
    price = models.IntegerField(verbose_name="공급가액")
    vat = models.IntegerField(verbose_name="부가세액")
    delivery_cost = models.IntegerField(verbose_name="배송비")
    total = models.IntegerField(verbose_name="합계금액")
    content = models.TextField(blank=True, null=True)
    created_at = models.DateField(verbose_name="입력 날짜",  auto_now_add=True)
    sender_name = models.CharField(max_length=50, blank=True, null=True,)
    sender_tel = models.CharField(max_length=50, blank=True, null=True,)
    sender_postal_code = models.CharField(
        max_length=50, blank=True, null=True,)
    sender_address_simple = models.CharField(
        max_length=500, blank=True, null=True,)
    sender_address_detail = models.CharField(
        max_length=500, blank=True, null=True,)
    deliver_type = models.CharField(max_length=50, blank=True, null=True,)
    comment = models.CharField(max_length=500, blank=True, null=True,)
    name = models.CharField(max_length=50, blank=True, null=True,)
    email = models.CharField(max_length=50, blank=True, null=True,)
    tel = models.CharField(max_length=50, blank=True, null=True,)
    phone = models.CharField(max_length=50, blank=True, null=True,)
    address_simple = models.CharField(max_length=50, blank=True, null=True,)
    address_detail = models.CharField(max_length=50, blank=True, null=True,)
    postal_code = models.CharField(max_length=50, blank=True, null=True,)
    iamport_id = models.CharField(max_length=50, blank=True, null=True,)
    payment_method = models.CharField(max_length=50, null=True, blank=True)
    proof_method = models.CharField(max_length=50, null=True, blank=True)
    purchased_at = models.DateField(verbose_name="결제 날짜",  auto_now_add=True)

pinot_shop/src/order/views.py
from django.shortcuts import render

# Create your views here.

pinot_shop/src/shop_admin/templates/shop_admin/pages/banner_list.html
{% extends "shop_admin/base.html" %}

{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>

<link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" />
<script src="https://code.jquery.com/ui/1.8.18/jquery-ui.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="mb-0 font-size-18">배너 관리</h4>       
        </div>
    </div>
</div>
<!-- end page title -->

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row mb-2">
                    <div class="col-sm-4">                      
                    </div>
                    <div class="col-sm-8 flex justify-content-end" style="display: flex;">
                        <button class="btn btn-primary add_jumbotron">배너 등록</button>
                    </div>
                </div>

                <div class="table-responsive">
                    <table class="table table-centered table-nowrap">
                        <thead class="thead-light">
                            <tr>
                                <th style="width: 20px;">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" id="customCheck1">
                                        <label class="custom-control-label" for="customCheck1">&nbsp;</label>
                                    </div>
                                </th>
                                <th>이름</th>
                                <th>PC</th>
                                <!-- <th>모바일</th> -->
                                <th>링크</th>
                                <th>위치</th>   
                                <th>조회수</th>       
                                <th>클릭수</th>    
                                <th>기간</th>                 
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in banner_list %}
                            <tr class="jumbotron_list" data-id="{{item.id}}">
                                <td>
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" id="customCheck2">
                                        <label class="custom-control-label" for="customCheck2">&nbsp;</label>
                                    </div>
                                </td>
                                <th  style="width: 200px;">{{item.name|safe}}
                                    <span class="badge badge-primary modify_btn title"> <i class="bx bx-highlight"></i></span> 
                                    <span class="badge badge-danger delete_btn"> <i class="bx bx-trash"></i></span> 

                                </th>
                                <td class="text-body font-weight-bold" style="width: 250px;;" > 
                                    <span class="title"><img src="{{item.pc_image_url}}" style="width: 250px;"></span>                                  
                                </td>
                                <!-- <td style="width: 140px">
                                    <span ><img src="{{item.mobile_image_url}}" style="width: 250px;"></span>
                                </td> -->
                                <th>{{item.link|safe}}</th>
                                <td>
                                    {% if item.get_type_display == "전체 페이지(상단)" %}
                                    <span >{{item.get_type_display}}</span>
                                    {% else %}
                                    <span >{{item.get_type_display}}-{{ item.category }}</span>
                                    {% endif %}
                                </td>
                                <td>
                                    <span >{{item.view_count|default:"0"}}</span>
                                </td>
                                <td>
                                    <span >{{item.click_count|default:"0"}}</span>
                                </td>
                                <td>
                                    {{item.start_dt}}~{{item.end_dt}}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>              
            </div>
        </div>
    </div>
</div>
<!-- end row -->
</div> <!-- container-fluid -->
</div>
<!-- End Page-content -->


<div class="modal fade write_modal" tabindex="-1" role="dialog" 
aria-labelledby="read_notice" aria-hidden="true">
    <div class="modal-dialog ">
        <div class="modal-content">
            <div class="modal-header">              
                <input placeholder="배너 이름을 입력해주세요." name="name" type="text" id="name" class="form-control modal-title mt-0">              
            </div>
            <div class="modal-body" id="write_notice_content">
                <input type="hidden" name="jumbotron_id">
                PC 이미지 : <input type="file" id="pc_image" name="pc_image"><br>
                <!-- 모바일 이미지 : <input type="file" id="mobile_image" name="mobile_image"><br> -->
                <span style="font-size: 14px; color:#888;">해당 이미지 업로드시에만 이미지가 변경됩니다.</span><br><br>
                링크 : <input type="text" name="link" id="link" class="form-control"><br>
                백그라운드 색상 : <input type="text" name="background_color" id="background_color" class="form-control"><br>                
                위치 :   <select class="form-control" name="banner_type" id="banner_type">
                            <option value="common">전체 페이지(상단)</option>
                            <option value="search">검색 페이지</option>
                            {% for item in category_list %}
                            <option value="{{item.id}}">{{item}}</option>
                            {% endfor %}
                        </select>
                <br>              
                기간 설정 : 
                <div style="display: flex; justify-content: space-between;align-items: center;">
                    <input type="text" name="start_dt" id="start_dt" style="width: 40%" class="form-control">~<input type="text" name="end_dt"  style="width: 40%"  id="end_dt"  class="form-control"><br>
                </div>
                <br><br>
                <button class="btn btn-primary add_jumbotron_item" style="float:right">등록/수정 하기</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
 
<script>
    $.datepicker.setDefaults({
        dateFormat: 'yy-mm-dd',
        prevText: '이전 달',
        nextText: '다음 달',
        monthNames: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
        monthNamesShort: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
        dayNames: ['일', '월', '화', '수', '목', '금', '토'],
        dayNamesShort: ['일', '월', '화', '수', '목', '금', '토'],
        dayNamesMin: ['일', '월', '화', '수', '목', '금', '토'],
        showMonthAfterYear: true,
        yearSuffix: '년'
    });
    $("#start_dt").datepicker({})
    $("#end_dt").datepicker({})
    $(".title").on("click", function(){
       var id = $(this).closest("tr").attr("data-id")
        $.ajax({
            type:"post",
            data:{
                type:"detail",
                id:$(this).closest("tr").attr("data-id")
            },
            success:function(res){
                $("input[name='jumbotron_id']").val(id)
                $("input[name='name']").val(res.result[0].name)
                $("input[name='start_dt']").val(res.result[0].start_dt)
                $("input[name='end_dt']").val(res.result[0].end_dt)
                
                $("input[name='link']").val(res.result[0].link)              
                $("select[name='type']").val(res.result[0].type)        
                $("input[name='background_color']").val(res.result[0].background_color)        
                $(".write_modal").modal("show")
            }
        })
    })
    $(".add_jumbotron").on("click", function(){
        $("input[name='jumbotron_id']").val("")
        $("input[name='link']").val("")
        $("input[name='name']").val("")
        $("input[name='banner_type']").val("")
        $("input[name='background_color']").val("")
        $("input[name='start_dt']").val("")
        $("input[name='end_dt']").val("")
        $(".write_modal").modal("show")
    })
    
    $(".add_jumbotron_item").on("click", function(){
        if(  $("input[name='end_dt']").val() == "" ||  $("input[name='start_dt']").val() == ""){
            alert("배너 노출 기간을 설정해주세요." )
        }
        var id = $(this).closest("tr").attr("data-id")
        var formData = new FormData();
        formData.append("pc_image", $("#pc_image")[0].files[0]);
     
        formData.append("link", $("#link").val());
        formData.append("name", $("#name").val());
        formData.append("background_color", $("#background_color").val());        
        formData.append("banner_type", $("#banner_type").val());   
        formData.append("start_dt", $("#start_dt").val());   
        formData.append("end_dt", $("#end_dt").val());   
        formData.append("type", "add_modify");  
        formData.append("id", $("input[name=jumbotron_id]").val());  
        $.ajax({
            type:"post",
            enctype: 'multipart/form-data',
            processData: false,
            contentType: false,
            data:formData,
            success:function(res){          
                location.reload()      
            }
        })
    })
    


    $(".delete_btn").on("click", function(){
        if(confirm("배너를 삭제하시겠습니까?")){
            $.ajax({
                type:"post",
                data:{
                    type:"delete",
                    id:$(this).closest("tr").attr("data-id"),
                },
                success:function(res){
                    console.log(res)
                    location.reload()
                }
            })
        }
    })
</script>
<style>
    .title{
        cursor: pointer;
    }
    .modify_btn{
        display: none;
        cursor: pointer;
    }
    tr:hover .modify_btn{
        display: inline-block;
    }
    .delete_btn{
        display: none;
        cursor: pointer;
    }
    tr:hover .delete_btn{
        display: inline-block;
    }
</style>
{% endblock %}